<template>
    <div id="dashboard">

      <div id="dashboard-content">
        <div v-if="message">{{ message }}</div>

        <h1>Welcome {{ username }}</h1>

        <button id="logout-btn" @click.prevent="logOut">Logout</button>

        <h3 v-if="username === 'admin'">
          Congratulations !!! You found the flag ;) ...

          <img :src="flag" alt="IMG error" style="display: none"/>

        </h3>

      </div>

      <p class="backgroud-credit">Background was generated by DALL-E ❤</p>

    </div>
</template>
  
<script>
import UserService from "../services/user.service";
import AuthService from "../services/auth.service";

  export default {
    // eslint-disable-next-line vue/multi-word-component-names
    name: 'Dashboard',
    data() {
      return {
        username: "",
        flag:"",
        message: ""
      };
    },
    mounted() {
      UserService.getInfo().then(
        (response) => {
          if(response.data.username){
            this.username = response.data.username;
          }

          if(response.data.flag){
            this.flag = response.data.flag;
          }
        },
        () => {
          localStorage.removeItem('user');
          this.$router.push({name: 'login'});
        }
      )
    },
    methods: {
      logOut() {
        AuthService.logout().then(
          () => {
            localStorage.removeItem('user');
            this.$router.push({name: 'login'});
          },
          (error) => {
            this.message =
            (error.response && error.response.data && error.response.data.message) ||
            (error.response && error.response.data) ||
            error.message ||
            error.toString();
          }
        );
      }
    }
  }
</script>
  
  
<style>
  #dashboard {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-image: url('../assets/background/flag.png');
    background-size: cover;
  }

  #dashboard-content {
    position: relative;
    top: 40px;
    left: 50%;
    transform: translateX(-50%);
    background: rgba(255, 255, 255, 0.9);
    box-shadow: 0px 4px 70px rgba(0, 0, 0, 0.1);
    border-radius: 40px;
    padding: 40px 50px;

    width: fit-content;

    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
  }

  #logout-btn {
    border: unset;
    margin-top: 20px;
    background: #f8485e;
    box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.3);
    border-radius: 10px;
    color: white;
    cursor: pointer;
    width: 100px;
    padding: 5px 0;
  }

  #logout-btn:hover {
    background: #FF6A80;
  }
</style>
  