<template>
    <div id="home">
      <div id="home-content">
        <h1>Coming soon ;)</h1>
        <img src="../assets/loading.svg" alt="Loading icon"/>
      </div>
      <p class="backgroud-credit">Background was generated by MidJourney feat DALL-E ❤</p>
    </div>
</template>
  
<script>
  export default {
    // eslint-disable-next-line vue/multi-word-component-names
    name: 'Home'
  }
</script>
  
  
<style>
  #home {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-image: url('../assets/background/main.png');
    background-size: cover;

    display: flex;
    align-items: center;
    justify-content: center;
  }


  #home-content {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    background: rgba(240, 240, 240, 0.7);
    padding: 40px 60px 0 60px;
    border-radius: 10%;
  }

  img {
    padding: 0;
  }
</style>
  