<template>
    <div id="login2">

      <Form  @submit="handleLogin" :validation-schema="schema">
        <h1>2FA code</h1>
        
        <div class="form-item">
          <label for="code">Code <strong>*</strong></label><br>
          <Field type="text" id="code" name="code" placeholder="Code" /><br>
          <ErrorMessage name="code" class="error-feedback" />
        </div>

        <div class="error-feedback" v-if="message">{{ message }}</div>


        <button :disabled="loading" id="button-submit">
          <span v-show="loading"></span>
              Validate</button>

      </Form>

    <div v-if="!twofaIsActive">
      <div v-if="qrcodeurl == ''" id="generate-code">
        <p>if is your first login, you need to generate a new 2FA instance</p>

        <button id="button-generated-code" :disabled="loading" @click="handleGenerateCode">
          <span v-show="loading"></span>
              Generate new 2FA instance</button>
      </div>
      <img v-else style="width:140px, height:auto" :src='qrcodeurl' alt="Qrcode Google Authentificator"/>
    </div>

    <p class="backgroud-credit">Background was generated by MidJourney feat DALL-E ❤</p>

    </div>
  </template>
  
<script>
import { Form, Field, ErrorMessage } from "vee-validate";
import * as yup from "yup";

import AuthService from '../services/auth.service'


export default {
  // eslint-disable-next-line vue/multi-word-component-names
  name: "Login2",
  components: {
    Form,
    Field,
    ErrorMessage,
  },
  data() {
    const schema = yup.object().shape({
      code: yup
        .string()
        .required("Code is required!")
        .matches(/^[0-9]+$/, "Must be only digits")
        .min(6, "Must be exactly 6 digits")
        .max(6, "Must be exactly 6 digits")
    });
    return {
      loading: false,
      message: "",
      schema,
      qrcodeurl: '',
      twofaIsActive: false
    };
  },
  created() {
    AuthService.loginWith2FA().then(
      (data) => {
        if(data.message != "You can try to login with 2FA") {
          this.$router.push({name: "login"});
        } else {
          const obj = JSON. parse(localStorage.getItem("user"));
          obj.username = data.username;
          localStorage.setItem("user", JSON.stringify(obj));

          this.twofaIsActive = data.twofaIsActive
        }
      },
      () => {
        this.$router.push({name: "login"});
      });
  },
  methods: {
    handleLogin(content) {

      AuthService.loginWith2FA(content.code).then(
        (data) => {
          if(data.message == "Authentication successful") {
            this.$router.push({name: "dashboard"});
          }

        },
        (error) => {
          this.message =
            (error.response && error.response.data && error.response.data.message) ||
            (error.response && error.response.data) ||
            error.message ||
            error.toString();
          this.loading = false;
        }
      );

    },
    handleGenerateCode() {
      AuthService.init2fa().then(
        (response) => {
          this.qrcodeurl = response.data.UrlQRCode
        },
        (error) => {
          this.message =
            (error.response && error.response.data && error.response.data.message) ||
            (error.response && error.response.data) ||
            error.message ||
            error.toString();
          this.loading = false;
        }
      );
    },
  },
}
</script>
  
  
<style>
  #login2 {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    width: 100vw;
    height: 100vh;

    background-image: url('../assets/background/main.png');
    background-size: cover;
  }

  h1 {
    margin: 0;
  }

  form {
    background: rgba(255, 255, 255, 0.9);
    box-shadow: 0px 4px 70px rgba(0, 0, 0, 0.1);
    border-radius: 40px;
    padding: 40px 50px;
    width: fit-content;
    height: fit-content;

    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 30px;
  }

  strong {
    color: #f8485e;
  }

  label {
    color: #333333;
  }

  input {
    border: unset;
    padding: 5px 12px;
    width: 250px;
  }


  input[type="number"]  {
    background: #FFFFFF;
    box-shadow: 4px 4px 5px rgba(61, 61, 58, 0.8);
    border-radius: 3px;
  }

  input[type="number"]:focus  {
    border: 1px solid #F8485E;
    outline: none;
  }

  #button-submit {
    border: unset;
    margin-top: 20px;
    background: #f8485e;
    box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.3);
    border-radius: 10px;
    color: white;
    cursor: pointer;
    width: 90%;
    padding: 5px 0;
  }

  #button-submit:hover {
    background: #FF6A80;
  }

  #button-generated-code {
    border: unset;
    background: #3d3d3a;
    box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.3);
    border-radius: 10px;
    color: white;
    cursor: pointer;
    padding: 5px 10px;
  }

  #button-generated-code:hover {
    background: #5a5a57;
  }

  .error-feedback {
    margin-top: 10px;
    color: #f8485e;
    font-size: 14px;
  }

  #generate-code {
    display: flex;
    flex-direction: column;
    align-items: center;
  }


</style>
  