<template>
    <div id="login">
      
      <Form  @submit="handleLogin" :validation-schema="schema">
        <h1>Test interface</h1>

        <div class="form-item">
          <label for="username">Username <strong>*</strong></label><br>
          <Field type="text" id="username" name="username" placeholder="Username" /><br>
          <ErrorMessage name="username" class="error-feedback" />
        </div>
        
        <div class="form-item">
          <label for="password">Password <strong>*</strong></label><br>
          <Field type="password" id="password" name="password" placeholder="Password" /><br>
          <ErrorMessage name="password" class="error-feedback" />
        </div>

        <button :disabled="loading" id="button-submit">
          <span v-show="loading"></span>
              Login</button>
          
        <div class="error-feedback" v-if="message">{{ message }}</div>

      </Form>

      <p class="backgroud-credit">Background was generated by MidJourney feat DALL-E ❤</p>

    </div>
  </template>
  
<script>
import { Form, Field, ErrorMessage } from "vee-validate";
import * as yup from "yup";
import AuthService from "../services/auth.service";


export default {
  // eslint-disable-next-line vue/multi-word-component-names
  name: "Login",
  components: {
    Form,
    Field,
    ErrorMessage,
  },
  data() {
    const schema = yup.object().shape({
      username: yup.string().required("Username is required!"),
      password: yup.string().required("Password is required!"),
    });
    return {
      loading: false,
      message: "",
      schema
    };
  },
  methods: {
    handleLogin(user) {
      this.loading = true;
      AuthService.login(user).then(
        () => {
          this.$router.push({name: "login2"});
        },
        (error) => {
          this.loading = false;
          this.message =
            (error.response && error.response.data && error.response.data.message) ||
            (error.response && error.response.data) ||
            error.message ||
            error.toString();
        }
      );
    },
  },
}
</script>
  
  
<style>
  #login {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    width: 100vw;
    height: 100vh;

    background-image: url('../assets/background/main.png');
    background-size: cover;
  }

  h1 {
    margin: 0;
  }

  form {
    background: rgba(255, 255, 255, 0.9);
    box-shadow: 0px 4px 70px rgba(0, 0, 0, 0.1);
    border-radius: 40px;
    padding: 40px 50px;
    width: fit-content;
    height: fit-content;

    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 30px;
  }

  strong {
    color: #f8485e;
  }

  label {
    color: #333333;
  }

  input {
    border: unset;
    padding: 5px 12px;
    width: 250px;
  }


  input[type="text"], input[type="password"]  {
    background: #FFFFFF;
    box-shadow: 4px 4px 5px rgba(61, 61, 58, 0.8);
    border-radius: 3px;
  }

  input[type="text"]:focus, input[type="password"]:focus  {
    border: 1px solid #F8485E;
    outline: none;
  }

  #button-submit {
    border: unset;
    margin-top: 20px;
    background: #f8485e;
    box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.3);
    border-radius: 10px;
    color: white;
    cursor: pointer;
    width: 90%;
    padding: 5px 0;
  }

  #button-submit:hover {
    background: #FF6A80;
  }


  .error-feedback {
    margin-top: 10px;
    color: #f8485e;
    font-size: 14px;
  }


</style>
  